#!/usr/bin/env python3
# Generate per-robot Gazebo topics, ROS bridge configs, and visible standby lines.

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SIMULATOR_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))
from dual_robot_geometry import DEFAULT_CONFIG, load_layout


def _base_sdf() -> Path:
    override = os.getenv("TURTLEBOT3_BURGER_SDF")
    if override:
        return Path(override)
    local = SIMULATOR_ROOT / "deps_ws" / "src" / "turtlebot3_simulations" / "turtlebot3_gazebo" / "models" / "turtlebot3_burger" / "model.sdf"
    if local.is_file():
        return local
    prefix = subprocess.check_output(["ros2", "pkg", "prefix", "turtlebot3_gazebo"], text=True).strip()
    return Path(prefix) / "share" / "turtlebot3_gazebo" / "models" / "turtlebot3_burger" / "model.sdf"


def _write_robot_sdf(base: Path, output: Path, robot_name: str) -> None:
    tree = ET.parse(base)
    replacements = {
        "imu": f"/{robot_name}/imu",
        "scan": f"/{robot_name}/scan",
        "cmd_vel": f"/{robot_name}/cmd_vel",
        "joint_states": f"/{robot_name}/joint_states",
    }
    for element in tree.iter():
        if element.tag == "topic" and (element.text or "").strip() in replacements:
            element.text = replacements[(element.text or "").strip()]
        elif element.tag == "odom_topic":
            element.text = f"/{robot_name}/odom"
        elif element.tag == "tf_topic":
            element.text = f"/{robot_name}/tf"
    output.parent.mkdir(parents=True, exist_ok=True)
    ET.indent(tree, space="  ")
    tree.write(output, encoding="utf-8", xml_declaration=True)


def _bridge_yaml(robot_name: str) -> str:
    entries = [
        ("clock", "clock", "rosgraph_msgs/msg/Clock", "gz.msgs.Clock", "GZ_TO_ROS", None),
        ("joint_states", f"/{robot_name}/joint_states", "sensor_msgs/msg/JointState", "gz.msgs.Model", "GZ_TO_ROS", None),
        ("odom", f"/{robot_name}/odom", "nav_msgs/msg/Odometry", "gz.msgs.Odometry", "GZ_TO_ROS", None),
        ("tf", f"/{robot_name}/tf", "tf2_msgs/msg/TFMessage", "gz.msgs.Pose_V", "GZ_TO_ROS", None),
        ("cmd_vel", f"/{robot_name}/cmd_vel", "geometry_msgs/msg/TwistStamped", "gz.msgs.Twist", "ROS_TO_GZ", None),
        ("imu", f"/{robot_name}/imu", "sensor_msgs/msg/Imu", "gz.msgs.IMU", "GZ_TO_ROS", "SENSOR_DATA"),
        ("scan", f"/{robot_name}/scan", "sensor_msgs/msg/LaserScan", "gz.msgs.LaserScan", "GZ_TO_ROS", "SENSOR_DATA"),
    ]
    lines = ["# Generated by generate_dual_robot_assets.py"]
    for ros_topic, gz_topic, ros_type, gz_type, direction, qos in entries:
        lines.extend([
            "",
            f"- ros_topic_name: \"{ros_topic}\"",
            f"  gz_topic_name: \"{gz_topic}\"",
            f"  ros_type_name: \"{ros_type}\"",
            f"  gz_type_name: \"{gz_type}\"",
            f"  direction: {direction}",
        ])
        if qos:
            lines.extend([f"  qos_profile: {qos}", "  lazy: false"])
    return "\n".join(lines) + "\n"


def _box_visual(link: ET.Element, name: str, pose: dict, color: str) -> None:
    visual = ET.SubElement(link, "visual", {"name": name})
    ET.SubElement(visual, "pose").text = "{:.6f} {:.6f} 0.004 0 0 {:.6f}".format(pose["x"], pose["y"], pose["yaw"])
    geometry = ET.SubElement(visual, "geometry")
    box = ET.SubElement(geometry, "box")
    ET.SubElement(box, "size").text = "0.015 0.180 0.008"
    material = ET.SubElement(visual, "material")
    ET.SubElement(material, "ambient").text = color
    ET.SubElement(material, "diffuse").text = color


def _add_standby_lines(world_path: Path, robots: list[dict]) -> None:
    tree = ET.parse(world_path)
    world = tree.getroot().find("world")
    if world is None:
        raise ValueError(f"world element missing: {world_path}")
    for existing in list(world.findall("model")):
        if existing.get("name") == "dual_robot_standby_lines":
            world.remove(existing)
    model = ET.SubElement(world, "model", {"name": "dual_robot_standby_lines"})
    ET.SubElement(model, "static").text = "true"
    link = ET.SubElement(model, "link", {"name": "lines"})
    for robot in robots:
        _box_visual(link, "{}_hold_20cm".format(robot["name"]), robot["hold_pose"], "0.95 0.45 0.05 1")
        _box_visual(link, "{}_approach_40cm".format(robot["name"]), robot["approach_pose"], "0.10 0.80 0.25 1")
    ET.indent(tree, space="  ")
    tree.write(world_path, encoding="utf-8", xml_declaration=True)


def generate(config: Path, world: Path, output_dir: Path) -> dict:
    layout = load_layout(config)
    base = _base_sdf()
    if not base.is_file():
        raise FileNotFoundError(base)
    output_dir.mkdir(parents=True, exist_ok=True)
    artifacts = []
    for robot in layout["robots"]:
        sdf = output_dir / "{}.sdf".format(robot["name"])
        bridge = output_dir / "{}_bridge.yaml".format(robot["name"])
        _write_robot_sdf(base, sdf, robot["name"])
        bridge.write_text(_bridge_yaml(robot["name"]), encoding="utf-8")
        artifacts.append({**robot, "sdf": str(sdf), "bridge_config": str(bridge)})
    _add_standby_lines(world, layout["robots"])
    manifest = {**layout, "world": str(world), "robots": artifacts}
    manifest_path = output_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--world", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, default=SIMULATOR_ROOT / "generated" / "dual_robot")
    args = parser.parse_args()
    manifest = generate(args.config, args.world.resolve(), args.output_dir.resolve())
    print(json.dumps(manifest, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
